apiVersion: v1
kind: Pod
metadata:
  name: restart-rules-example
spec:
  restartPolicy: Never   # policy generale del Pod
  containers:
  - name: container-ok
    image: alpine
    command: ["sh", "-c", "echo Uscita con 0 && exit 0"]
    restartPolicy:
      rules:
        - onExitCodes:
            containerName: container-ok
            operator: In
            values: [0]
          action: Restart
  - name: container-ko
    image: alpine
    command: ["sh", "-c", "echo Uscita con 1 && exit 1"]
    restartPolicy:
      rules:
        - onExitCodes:
            containerName: container-ko
            operator: In
            values: [1]
          action: Restart
