apiVersion: v1
kind: Pod
metadata:
  name: image-volume-test
spec:
  containers:
  - name: app
    image: busybox
    command: ["cat", "/data/hello.txt"]
    volumeMounts:
    - name: imgvol
      mountPath: /data
  volumes:
  - name: imgvol
    image:
      reference: docker.io/library/testdata:latest
