apiVersion: v1
kind: Pod
metadata:
  name: image-volume-fallback
spec:
  volumes:
  - name: data
    emptyDir: {}
  initContainers:
  - name: init
    image: busybox
    command: ["sh", "-c", "echo 'Hello from image!' > /data/hello.txt"]
    volumeMounts:
    - name: data
      mountPath: /data
  containers:
  - name: app
    image: busybox
    command: ["cat", "/data/hello.txt"]
    volumeMounts:
    - name: data
      mountPath: /data
