apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-topology
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-topology
  template:
    metadata:
      labels:
        app: nginx-topology
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-topology-svc
  namespace: default
spec:
  selector:
    app: nginx-topology
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  internalTrafficPolicy: PreferSameNode
