apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-cluster-nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: test-cluster-nginx
  template:
    metadata:
      labels:
        app: test-cluster-nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: test-cluster-nginx
spec:
  selector:
    app: test-cluster-nginx
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP
